name: Linux

on:
  push:
    branches:
      - '**'
  release:
    types:
      - created

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  checkout:
    runs-on: linux

    steps:
      - uses: actions/checkout@v2

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build-linux -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build Test
        run: cmake --build build-linux --target all -- -j 9

      - name: Run Test
        working-directory: ${{github.workspace}}/build-linux
        run: ctest -C ${{env.BUILD_TYPE}} --extra-verbose --output-on-failure
